[workspace]
members = [
    "chapter-1/*",
    "chapter-2/*",
    "chapter-3/*",
    "projects/*",
    "chapter-4/*",
    "chapter-5/*",
    "chapter-6/*",
    "chapter-7/*", "package_and_crates",
]
resolver = "2"
